version: '3.9'

volumes:
  cache:
    driver: local

services:
  app:
    build:
      context: .
    container_name: pastebin-application
    depends_on:
      - db
      - redis
#      - minio
    env_file:
      - .env
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin?currentSchema=pastebin_schema
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=1234
    ports:
      - '8080:8080'

  db:
    image: postgres:13-alpine
    container_name: pastebin-db-docker #это хост
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    restart: always
    container_name: redis-docker #и это хост
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    volumes:
      - cache:/data