version: '3.9'

volumes:
  cache:
    driver: local
  minio-data:
    driver: local


services:

  minio:
    image: minio/minio:latest
    container_name: minio-docker
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/minio

  redis:
    image: redis:7.4-rc-alpine
    restart: always
    container_name: redis-docker #и это хост
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    volumes:
      - cache:/data