server:
  port: 8080

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger/pastebin-ui
  api-docs:
    path: /swagger/pastebin-api

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1 #часов
    refresh: 30 #дней

minio:
  url: ${MINIO_URL}
  bucket: ${MINIO_BUCKET}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}

spring:

  config:
    import: optional:file:.env[.properties]

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    # по-хорошему, вместо пересоздания БД должны быть сиды для инициализации
    database: POSTGRESQL

