#docker run --name pastebin-db-only -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=pastebin -d postgres
#docker exec -ti pastebin-db-only psql -U root -d pastebin

#  для создания схем (чтобы не использовать публичную):
#  1) в консоли пишем -->> create schema pastebin_schema;
#  2) потом добавляем пути -->> SET search_path = public, pastebin_schema;
#  3) проверяем -->> \dn покажет все схемы
#  4) потом запуск прилаги
#  5) \d покажет вообще все таблицы (с разных схем);
#  нам важно только знать, что есть схема и что ей принадлежат наши таблицы

#was using (full):
#docker run -p 9000:9000 -p 9001:9001 --name minio-result -v D:\minio\data:/data -e "MINIO_ROOT_USER=root" -e "MINIO_ROOT_PASSWORD=root" quay.io/minio/minio server /data --console-address ":9001"

#РЕАЛИЗОВАН ДОКЕР КОМПОУЗ
#само по себе приложение работает с бд в pastebin-db-only
# в композ файле свой контейнер с БД;
# но есть проблема: параллельно всегда должен быть запущен редис, тк по коду проверка идет в нем.
server:
  port: 8080

springdoc:
  override-with-generic-response: false
  swagger-ui:
    path: /swagger/pastebin-ui
  api-docs:
    path: /swagger/pastebin-api


spring:

  config:
    import: optional:file:.env[.properties]

#для sql, я удалил, тк мне лучше сделать входные в коде
#мб к сдаче поменяю
#  sql:
#    init:
#      mode: always
#      continue-on-error: false
#      data-locations:
#        - classpath:schema.sql
#        - classpath:demo_data.sql

  cache:
    type: redis
  data:
    redis:
#      host: ${REDIS_HOST} #ЗДЕСЬ ДОЛЖЕН БЫТЬ CONTAINER_NAME С REDIS, ТК ХОСТ НЕ ЛОКАЛЬНО
      host: localhost #ЗДЕСЬ ДОЛЖЕН БЫТЬ CONTAINER_NAME С REDIS, ТК ХОСТ НЕ ЛОКАЛЬНО
      port: 6379
      password: ${REDIS_PASSWORD}


  datasource:
#    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    url: jdbc:postgresql://localhost:5432/pastebin?currentSchema=pastebin_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    database: POSTGRESQL

security:
  jwt:
    secret: ${JWT_SECRET}
    access: 1 #${JWT_ACCESS} #часов
    refresh: 30 #${JWT_REFRESH} #дней

  #чисто админовское
  #login: minioadmin <---> pass: minioadmin
minio:
  bucket: ${MINIO_BUCKET}
  url: ${MINIO_URL} #либо сюда, либо в композе указывать может надо будет указать имя контейнера
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}



